spring.application.name=First-day-project

# DataSource 설정 - EC2 Docker MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://54.180.118.14:3307/firstday?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=firstday_user
spring.datasource.password=1q2w3E4R!

# JPA 설정
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MyBatis 설정
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=kr.co.firstday
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL

# Thymeleaf 설정
spring.thymeleaf.cache=false

# Ollama 설정
spring.ai.model.chat=ollama
spring.ai.model.embedding=ollama

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.model=qwen3.5:9b
spring.ai.ollama.chat.think=false
spring.ai.ollama.chat.temperature=0.3
spring.ai.ollama.chat.num-ctx=8192

spring.ai.ollama.embedding.model=qwen3-embedding:0.6b
spring.ai.ollama.init.pull-model-strategy=never


# PGvector 임시 비활성화
spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration


# 로그 설정
logging.level.root=INFO
logging.level.kr.co.firstday=DEBUG
logging.level.org.mybatis=DEBUG
logging.level.org.springframework.security=INFO