# /etc/httpd/conf.d/firstday.conf
# 수집일: 2026-08-24

<VirtualHost *:80>
    ServerName firstdayproject.site
    ServerAlias www.firstdayproject.site

    Redirect permanent / https://firstdayproject.site/

    ErrorLog  /var/log/httpd/firstday-error.log
    CustomLog /var/log/httpd/firstday-access.log combined
</VirtualHost>
